version: "3.9"

services:
    
  api:
    image: keskonbouf_api:latest
    container_name: api
    ports:
    - 8000:8000
    environment:
      - mongoUser=${mongoUser}
      - mongoPass=${mongoPass}

  front:
    image: keskonbouf_front:latest
    container_name: front
    depends_on:
      - api
    ports:
    - 8501:8501
