apiVersion: apps/v1
kind: Deployment
metadata:
  name: keskonbouf-api
  labels:
    app: keskonbouf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keskonbouf
  template:
    metadata:
      labels:
        app: keskonbouf
    spec:
      containers:
      - name: api
        image: keskonbouf_api:latest
        imagePullPolicy: Never
        ports:
        -containerPort: 8000
        env:
        - name: mongoUser
          valueFrom:
            secretKeyRef:
              name: mongouser
              key: User
        - name: mongoPass
          valueFrom:
            secretKeyRef:
              name : mongopass
              key : mongoPass
