apiVersion: apps/v1
kind: Deployment
metadata:
  name: keskonbouf-front
  labels:
    app: keskonbouf-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keskonbouf-front
  template:
    metadata:
      labels:
        app: keskonbouf-front
    spec:
      containers:
      - name: front
        image: cafetiere/keskonbouf_front:latest
        imagePullPolicy: Always
        ports:
        -containerPort: 8501