apiVersion: v1
kind: Service
metadata:
  name: jenkins #name of the Jenkins Kubernetes Service
spec:
  type: NodePort #Type of the Jenkins Kubernetes Service
  ports:
  - port: 8080 #port for the Jenkins Kubernetes Service
    targetPort: 8080 #port for the Jenkins pod
  selector:
    app: jenkins