FROM python:3.11

WORKDIR /streamlit

COPY ./requirements.txt .
COPY ./pages ./pages/
COPY ./main.py .

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

RUN streamlit run streamlit_front/main.python

