FROM python:3.11

WORKDIR /api

COPY ./requirements.txt .

COPY mongodbconnect.py .

COPY ./main.py .

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

CMD python3 main.py

